version: "3.9"

services:
  database:
    container_name: my_database
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: restaurant_app
      POSTGRES_USER: restaurant_user
      POSTGRES_PASSWORD: restaurant_user_pass
      POSTGRES_ROOT_PASSWORD: rootpass
      POSTGRES_PORT: 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - "5433:5432"