spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/restaurant_app
    username: restaurant_user
    password: restaurant_user_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl