spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Restaurant_API
    username: restaurant_app
    password: restaurantpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
